name: Submit SNS Proposal
on:
  push:
    branches:
      - main

jobs:
  submit_upgrade_proposal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: "true"

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
            dfx-version: "0.16.1"

      - name: Confirm successful installation
        run: dfx --version

      - name: Import DFX identity
        run: |
          touch actions_identity.pem
          echo "${{ secrets.ESTATE_DAO_SNS_PROPOSAL_SUBMITTER_PRIVATE_KEY }}" > actions_identity.pem
          dfx identity import --storage-mode=plaintext actions actions_identity.pem
          dfx identity use actions

      - name: Build
        run: |
            cd provision_canister
            rustup target add wasm32-unknown-unknown
            dfx build provision_canister_backend --network=ic
            hash=$(sha256sum < .dfx/ic/canisters/provision_canister_backend/provision_canister_backend.wasm)
            echo "Module Hash: ${hash}"

      - name: Install quill from GitHub Releases
        run: |
            curl -LJO https://github.com/dfinity/quill/releases/download/v0.4.2/quill-linux-x86_64-musl
            mv quill-linux-x86_64-musl quill
            chmod +x quill

      - name: create an SNS proposal to upgrade the canister
        run: |
            cd provision_canister
            CANISTER_NAME=provision_canister_backend
            export CANISTER_ID=$(dfx canister id ${CANISTER_NAME} --network=ic)
            mkdir -p "proposals/${CANISTER_NAME}"
            touch "proposals/${CANISTER_NAME}/upgrade.json"
            ./quill sns \
                --canister-ids-file ./sns_canister_ids.json \
                --pem-file actions_identity.pem \
                make-upgrade-canister-proposal \
                --title "Upgrade ${CANISTER_NAME} Canisters" \
                --summary "Upgrade ${CANISTER_NAME}" \
                --url 'https://wbdy5-yyaaa-aaaap-abysq-cai.icp0.io/' \
                --target-canister-id $CANISTER_ID \
                --wasm-path .dfx/ic/canisters/${CANISTER_NAME}/${CANISTER_NAME}.wasm \
                ${{ secrets.ESTATE_DAO_SNS_PROPOSAL_SUBMITTER_NEURON_ID }} > "proposals/${CANISTER_NAME}/upgrade.json"
            ./quill send proposals/${CANISTER_NAME}/upgrade.json --yes
      

