name: Test
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-client-deploy-dapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.16.1"

      - name: Confirm successful installation
        run: dfx --version

      - name: Start DFX Server
        run: dfx start --background

      - name: Test DFX connection
        run: dfx ping http://localhost:4943

      # - name: Run test
      #   run: test

      - name: build and deploy Canister
        run: |
          cd provision_canister
          dfx build provision_canister_backend
          dfx deploy provision_canister_backend

      - name: call upload script
        run: |
          cd ../scripts/
          ./canister_deploy_local.sh
              
